const express =require('express');
const Router =express();
const bodyParser=require('body-parser');
const ProductController=require('../Controllers/Product');
const Controller = new ProductController();
const Token=require('../Controllers/ToKen');
const ControllerToken=new Token();
Router.use(express.json());
Router.use(bodyParser.urlencoded({ extended: true }));

        Router.get('/', Controller.findAll);
        Router.get('/Product/pagecountProduct', Controller.pagecountfindAll);
        Router.get('/:id', Controller.findOne);
        Router.get('/Product/findItem/:page', Controller.findItem);
        Router.get('/Product/countpagefindItem', Controller.countpagefindItem);
        Router.get('/Product/searchbyprice/:page', Controller.searchbyprice);
        Router.get('/Product/countpagesearchbyprice', Controller.countpagesearchbyprice);
        Router.get('/Product/searchbypriceBetween/:page', Controller.searchbypriceBetween);
        Router.get('/Product/countpagesearchbypriceBetween',Controller.countpagesearchbypriceBetween);
        Router.get('/Product/searchbyname/:page',Controller.searchbyname);
        Router.get('/Product/countpagesearchbyname',Controller.countpagesearchbyname);
        Router.get('/Product/searchbycategory/:page',Controller.searchbycategory);
        Router.get('/Product/countpagesearchbycategory',Controller.countpagesearchbycategory);
        Router.get('/Product/findArrayProduct',Controller.findArrayProduct);
        Router.get('/Product/countpagefindDetailsProduct',Controller.countpagefindDetailsProduct);
        Router.get('/Product/findDetailsProduct/:page',Controller.findDetailsProduct);
        
        Router.post('/Product/CheckProduct',Controller.CheckProduct);
        Router.post('/',ControllerToken.RoleAdmin,ControllerToken.CheckToKenTime,Controller.create);
        Router.put('/:id',ControllerToken.RoleAdmin,ControllerToken.CheckToKenTime,Controller.update);
        Router.put('/Product/UpdateQuantityArrayProduct',ControllerToken.RoleUser,ControllerToken.CheckToKenTime,Controller.UpdateQuantity);
        Router.delete('/:id',ControllerToken.RoleAdmin,ControllerToken.CheckToKenTime,Controller.delete);
module.exports= Router;